api_platform:
    title: API Platform Project
    version: 1.0.0
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    patch_formats:
        json: ['application/merge-patch+json']
    error_formats:
        jsonproblem: ['application/problem+json']
        jsonld: ['application/ld+json']

