doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be in the App namespace
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false

